### ISSUE TITLE
Add ReadME and topics

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/sidewalk-widths#1]
Please include information about project description, instructions, tech/tools, and any relevant links/repos

**Comment by impiaaa** [comment]
Is that better? This is a "finished" project so I don't expect new volunteers.

**Comment by ychoy** [comment]
@impiaaa can you add some information about it being a completed project in the description?

**Comment by impiaaa** [comment]
@ychoy Added to the readme.

**Comment by ychoy** [comment]
Thanks Spencer!
